ln -s ~/Dropbox/dotfiles/.atom ~/.atom
ln -s ~/Dropbox/dotfiles/.config ~/.config
ln -s ~/Dropbox/dotfiles/.gemrc ~/.gemrc
ln -s ~/Dropbox/dotfiles/.gitconfig ~/.gitconfig
ln -s ~/Dropbox/dotfiles/.irbrc ~/.irbrc
ln -s ~/Dropbox/dotfiles/.screenrc ~/.screenrc
ln -s ~/Dropbox/dotfiles/.ssh ~/.ssh
ln -s ~/Dropbox/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/Dropbox/dotfiles/.vim ~/.vim
ln -s ~/Dropbox/dotfiles/.vimrc ~/.vimrc
ln -s ~/Dropbox/dotfiles/.zshenv ~/.zshenv
ln -s ~/Dropbox/dotfiles/.zshrc ~/.zshrC
